[package]
name = "karl-common"
version = "0.1.0"
authors = ["Gina Yuan <gina.yuan@gmail.com>"]
edition = "2018"

[features]
default = []

[dependencies]
serde = { version = "1.0",  features = ["derive"] }
serde_json = "1.0"
flate2 = "1.0.17"
tar = "0.4.30"
rand = "0.8"
tonic = "0.4"
prost = "0.7"

[build-dependencies]
tonic-build = "0.4"

[dev-dependencies]
tempdir = "0.3"
