[package]
name = "karl"
version = "0.1.0"
authors = ["Gina Yuan <gina.yuan@gmail.com>"]
edition = "2018"

[dependencies]
wasmer = { path = "wasmer" }
bincode = "1.3.1"
futures-util = "0.3.5"
mdns = "1.1.0"
serde = "1.0.115"
tempdir = "0.3"
tokio = { version = "0.2", features = ["rt-threaded"] }
zip = "0.5.6"
