[package]
name = "karl"
version = "0.1.0"
authors = ["Gina Yuan <gina.yuan@gmail.com>"]
edition = "2018"

[dependencies.wasmer]
path = "submodules/wasmer"
default-features = false
features = ["backend-cranelift", "wasi"]

[dependencies]
astro-dnssd = { path = "submodules/astro-dnssd" }
wapm-cli = { path = "submodules/wapm-cli" }
bincode = "1.3.1"
env_logger = "0.7"
log = "0.4"
serde = "1.0.115"
tempdir = "0.3"
tokio = { version = "0.2", features = ["rt-threaded"] }
flate2 = "1.0.17"
tar = "0.4.30"
sys-mount = "1.2.1"

[dev-dependencies]
clap = "2.33.3"
dirs = "1.0.5"
rand = "0.7.3"

[[example]]
name = "service"
crate-type = ["bin"]

[[example]]
name = "parallel"
crate-type = ["bin"]
